export default {
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "#108194",
          hover: "#0d6a78",
          active: "#0B5F6E",
          soft: "#E6F7FA",
          subtle: "#F0FBFC",
          border: "#B9E5EA",
        },
        text: {
          primary: "#1D293D",
          secondary: "#45556C",
          muted: "#64748B",
          placeholder: "#90A1B9",
          disabled: "#CBD5E1",
          inverse: "#FFFFFF",
        },
        success: {
          DEFAULT: "#198A63",
          bg: "#B7EEDB",
          text: "#198A63",
          border: "#9BE4CD",
        },
        warning: {
          DEFAULT: "#EF3530",
          bg: "#FFE6E5",
          text: "#EF3530",
          border: "#FECACA",
        },
        // 編輯狀態 (橘色系) — 對應 Figma 規格
        edit: {
          DEFAULT: "#E27600",
          bg: "#FDE8C2",
          text: "#E27600",
          border: "#FDE8C2",
        },
        // 駁回狀態 — 依 Figma 與編輯共用同一橘色系
        rejected: {
          DEFAULT: "#E27600",
          bg: "#FDE8C2",
          text: "#E27600",
          border: "#FDE8C2",
        },
        danger: {
          DEFAULT: "#EF3530",
          bg: "#FFE6E5",
          text: "#EF3530",
          border: "#FECACA",
        },
        state: {
          red: "#EF5350",
        },
        info: {
          DEFAULT: "#2889D3",
          bg: "#E1F2FF",
          text: "#1570A6",
          border: "#B7E0FA",
        },
        natural: {
          DEFAULT: "#4B5563",
          bg: "#E5E7EB",
          text: "#4B5563",
          border: "#CBD5E1",
          grey: "#D1D5DB",
        },
        border: {
          DEFAULT: "#E2E8F0",
          muted: "#EEF2F6",
          strong: "#CBD5E1",
          focus: "#108194",
          error: "#EF3530",
          disabled: "#CBD5E1",
        },
        background: {
          page: "#F8FAFC",
          surface: "#FFFFFF",
          subtle: "#F1F5F9",
          hover: "#F8FAFC",
          disabled: "#F1F5F9",
          overlay: "rgba(15, 23, 42, 0.45)",
        },
        login: {
          bell: "#F5B81D",
          "dot-1": "#7DBCCB",
          "dot-2": "#4BC7DD",
          "dot-3": "#22BFAE",
        },
      },
      spacing: {
        sidebar: "252px",
        "sidebar-gutter": "15px",
        "sidebar-logo": "88px",
        "sidebar-item": "39px",
        "sidebar-child": "43px",
        header: "72px",
        "logo-bank-w": "150px",
        "logo-bank-h": "31px",
        "modal-password": "448px",
        "modal-md": "640px",
        "modal-lg": "680px",
        "modal-xl": "960px",
        "modal-max": "calc(100vw - 32px)",
        "modal-history": "1152px",
        "modal-history-max": "calc(100vh - 48px)",
        "modal-history-search": "456px",
        "modal-date": "184px",
        "col-date": "30%",
        "col-operator": "30%",
        "col-module": "24%",
        "col-action": "128px",
        "filter-sm": "180px",
        "filter-md": "220px",
        "filter-lg": "240px",
        "filter-xl": "260px",
        "form-card": "560px",
        "list-title": "260px",
      },
      boxShadow: {
        control:
          "0 1px 1.5px rgb(0 0 0 / 10%), 0 1px 1px rgb(0 0 0 / 10%)",
        card: "0 10px 24px rgb(16 129 148 / 6%)",
        "card-soft": "0 10px 24px rgb(16 129 148 / 5%)",
        popup: "0 25px 50px -12px rgb(0 0 0 / 25%)",
      },
    },
  },
};
